#!/bin/sh

set -eu

AUTH_CODE="$1"

TOKEN_URL="https://api.moves-app.com/oauth/v1/access_token?grant_type=authorization_code&code=${AUTH_CODE}&client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&redirect_uri=${REDIRECT_URI}"

curl -sSLv -X POST "$TOKEN_URL"
